apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: red-team
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  liveness:
    path: isalive
  readiness:
    path: isalive
  resources:
    limits:
      cpu: 5000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 512Mi
  ingresses:
    - https://red-team.intern.nav.no
  replicas:
    min: 1
    max: 1
  filesFrom:
    - configmap: red-team-data
      mountPath: /var/run/configmaps
  accessPolicy:
    inbound:
      rules:
        - application: tbd-website